### ISSUE TITLE
'and __slackpuppet_bot' appeared in a 1-on-1 channel name

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#10]
chat with just one person. also defaulted to being a room when it should have been a people

![image](https://user-images.githubusercontent.com/1048265/60632339-e18aee80-9db9-11e9-819c-ee3630a4fa69.png)

**Comment by Sorunome** [comment]
did you start the conversation via slack and had double-puppeting on by chance? If so, that is intended behaviour as some namespaced user is needed to be able to transmit messages. As soon you'll be able to initiate from the matrix side it should be fine?

**Comment by ericmigi** [comment]
Yes, I did start this convo on the slack side. But I feel like a lot of people may do so, for ex they may use the bridge on desktop but continue to use the slack app on mobile. Could the bot be a ghost in this case?

**Comment by Sorunome** [comment]
They should auto-leave by now after the other party on slack says something
