### ISSUE TITLE
Support topic updates

### ISSUE THREAD

**Issue by twouters** [Sorunome/mx-puppet-slack#102]
Slack sends message events with [channel_topic](https://api.slack.com/events/message/channel_topic) or [group_topic](https://api.slack.com/events/message/group_topic) when someone changes a room's topic.

[soru-slack-client](https://github.com/Sorunome/soru-slack-client) could detect these and update the room topic on matrix's end.

**Comment by Sorunome** [comment]
done in https://github.com/Sorunome/soru-slack-client/commit/6f34098645dc9a2432113fd8a3de9186f74d9f4d
