### ISSUE TITLE
how to initiate a DM conversation with a slack contact?

### ISSUE THREAD

**Issue by loganringer** [Sorunome/mx-puppet-slack#111]
If I message someone on the slack app, their DM is pulled into matrix, but how do I initiate a DM conversation from the matrix side?
Also, when I do listrooms in the slack puppet bridge chat, it only shows the channels, and not the DMs.

**Comment by loganringer** [comment]
also, when I do listrooms in the slack puppet bridge chat, it only shows the channels, and not the DMs.

**Comment by Sorunome** [comment]
Either click on a user and start a dm with them from an existing bridged chat or type `listusers` and then click on a pill and start a chat that way

**Comment by loganringer** [comment]
Sure, but when I do listusers, the chat is created, and then it instantly says the person has left the room.

**Comment by Sorunome** [comment]
that indicates a setup failure. Please ask for support like this in the matrix room
