### ISSUE TITLE
Sent newlines are lost Slack-side

### ISSUE THREAD

**Issue by yousefamar** [Sorunome/mx-puppet-slack#112]
I had a look through the existing issues and couldn't find this bug. It's related to #14, but the other way around. To reproduce, send a message with newlines / line breaks in it, and in Slack these will be gone (with no indication except when you actually open Slack and check), the message squeezed into one line. For context, I'm using Element Desktop as a client

**Comment by Sorunome** [comment]
They are resolved here? Sent from element:

![Screenshot_2021-03-02_19-42-47](https://user-images.githubusercontent.com/2433620/109698238-7fd2e700-7b8f-11eb-84bc-08e11a7080e2.png)

formatted on slack side:

![Screenshot_2021-03-02_19-43-11](https://user-images.githubusercontent.com/2433620/109698282-8c573f80-7b8f-11eb-8843-e51d23880e91.png)

slack just seems to have a lower font height for completely blank lines

**Comment by yousefamar** [comment]
I have more information on how to reliably reproduce this now:

![image](https://user-images.githubusercontent.com/999235/109811841-38963600-7c23-11eb-9d4a-ef43bc80de26.png)

![image](https://user-images.githubusercontent.com/999235/109811868-41870780-7c23-11eb-8026-0ac02b89d6eb.png)

**Comment by yousefamar** [comment]
@Sorunome any chance we can reopen this? It also affects any message when you edit it by the way:

Original message on Element Desktop and Slack Desktop respectively:

![image](https://user-images.githubusercontent.com/999235/115029712-2b28c880-9ebe-11eb-8b1f-763381140d0f.png)

![image](https://user-images.githubusercontent.com/999235/115029768-38de4e00-9ebe-11eb-975c-fa7f59113e13.png)

Message after it has been edited:

![image](https://user-images.githubusercontent.com/999235/115029819-4a275a80-9ebe-11eb-8097-f1a3a05fd7b9.png)

![image](https://user-images.githubusercontent.com/999235/115029856-53182c00-9ebe-11eb-83a4-b279f7d34a76.png)

**Comment by Sorunome** [comment]
soru doesn't have github access much lately, mind making a new issue?

16. 4. 2021 15:16:55 Yousef Amar ***@***.***>:
