### ISSUE TITLE
Failure to Link

### ISSUE THREAD

**Issue by sek22** [Sorunome/mx-puppet-slack#113]
I have setup the project locally and inside docker. The bot comes up as a user in matrix but does not respond to the link message in matrix. I am also behind a firewall if that makes any difference. Is there anything specific to add on the slack side of things or what am I missing?
![image](https://user-images.githubusercontent.com/78108759/109536381-a60f5e80-7a8b-11eb-8d54-e7dbbd906d8e.png)
![image](https://user-images.githubusercontent.com/78108759/109536445-ba535b80-7a8b-11eb-8b86-75720eabdfd6.png)

Let me know if there is any more information that is required from my end. 
Thanks.

**Comment by Sorunome** [comment]
your slack puppet never accepted the invite, indicating that communication from your homeserver to the bridge isn't working. Please use the support chat for support instead of github issues.
