### ISSUE TITLE
user.profile.display_name can be empty

### ISSUE THREAD

**Issue by twouters** [Sorunome/mx-puppet-slack#16]
Possible fallbacks are:

user.profile.real_name
user.profile.real_name_normalized (non-latin chars stripped)
user.real_name
user.name

https://github.com/Sorunome/mx-puppet-slack/blob/c21b8bfcc8e260017a2634be9139f82ef77fb754/src/slack.ts#L51

**Comment by Sorunome** [comment]
Done in https://github.com/Sorunome/mx-puppet-slack/commit/cd24043af14ee409dd53b41cf780402859fadfbf
