### ISSUE TITLE
run_docker.sh enforces name of registration file

### ISSUE THREAD

**Issue by Cadair** [Sorunome/mx-puppet-slack#23]
if you don't want your registration file to be `slack-registration.yaml` the script wont generate a registration file or run the bridge with the correct registration file.

**Comment by Sorunome** [comment]
No idea how to do docker stuff, help would be appreciated!

**Comment by Cadair** [comment]
I am not sure I know enough to come up with a robust alternative either.

**Comment by zoglesby** [comment]
Check and env variable, if its empty set it to the current default. Use the env variable in the start command.

I think that would work, but without testing I am not 100%

**Comment by Sorunome** [comment]
this should be fixed in https://github.com/Sorunome/mx-puppet-slack/commit/38035fce60afea11ec5bd89918056d04b5777723
