### ISSUE TITLE
Filter out subtype: 'channel_join'

### ISSUE THREAD

**Issue by Sorunome** [Sorunome/mx-puppet-slack#25]
those pesky "user has joined" messages

**Comment by Sorunome** [comment]
https://sorunome.de/_matrix/media/r0/download/maunium.net/qHNQvVAIcMPNwEWpCsKZArsM

**Comment by Cadair** [comment]
Came here to say this :grin:

**Comment by Sorunome** [comment]
Done in https://github.com/Sorunome/mx-puppet-slack/commit/479159d5650df7feb61bd28d27f68f607ac049fa
