### ISSUE TITLE
Clear typing notification when message received

### ISSUE THREAD

**Issue by twouters** [Sorunome/mx-puppet-slack#28]
Typing notifications remain active while the message has already been delivered.
This can be confusing as it appears that the user is typing another message until the default timeout has been reached.

**Comment by twouters** [comment]
Fixed with Sorunome/mx-puppet-bridge@5cccbffe7c4e97910f6d4b6885089d739a5295ec

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-slack/commit/9eba3517bc3ab1c52e1033c3adad021a84d76ad0
