### ISSUE TITLE
Multiple Workspaces?

### ISSUE THREAD

**Issue by paulbdavis** [Sorunome/mx-puppet-slack#30]
It seems like it's not possible to set up multiple apps for multiple workspaces (as they each have their own oauth stuff)

Is this something that could/will be implemented? Or is it best to just run multiple instances of the bridge, one per workspace?

**Comment by Sorunome** [comment]
run the link command multiple times with multiple tokens!

Am 17. Januar 2020 23:46:00 MEZ schrieb Paul Davis <notifications@github.com>:

**Comment by paulbdavis** [comment]
Ah, I guess I meant when using the oauth stuff instead of the legacy tokens. 

Paul Davis
github.com/dangersalad
github.com/Paul Davis

**Comment by Sorunome** [comment]
we'd have to ask @tulir as he wrote the oauth stuffs

**Comment by tulir** [comment]
Why do you need separate apps? The same app worked fine for all workspaces for me

**Comment by Sorunome** [comment]
poke @paulbdavis

**Comment by joao-p-marques** [comment]
Hi! 

I know this issue is closed, but I am having some trouble setting up the Slack App. It works perfectly on 1 workspace, but if I want to add it to another, I need to enable distribution. 

The problem is I need to set up permissions for the app. Which ones should I pick?

I think this is not directly related to the bridge, but is more a Slack problem...

**Comment by Sorunome** [comment]
How are you trying multiple workspaces? In puppet mode or relay mode?

**Comment by joao-p-marques** [comment]
I am using the default puppet config

**Comment by Sorunome** [comment]
So you are talking about that oauth block, then? Why do you need to enable distirbution? The oauth link that mx-puppet-slack generates already includes a scope

ANyhow, it is using the scope called `client` which is by now a legacy scope https://api.slack.com/scopes/client selecting a bunch of user scopes instead will probably work, too

**Comment by tulir** [comment]
The permissions shouldn't matter, it always allows using the `client` scope regardless of what you pick.

> Why do you need to enable distirbution?

To use it in multiple workspaces

**Comment by joao-p-marques** [comment]
Yes, I am using Oauth. I also have very little experience with Slack apps, so I don't really know how to make the app work for several Workspaces.

The app I created is [exclusive to a single workspace](https://api.slack.com/start/distributing#multi_workspace_apps), and the client Id and Secret is also exclusive to that workspace, right? 

Is there any alternative to adding all the current scopes?

**Comment by joao-p-marques** [comment]
> The permissions shouldn't matter, it always allows using the `client` scope regardless of what you pick.

As @Sorunome said, that is now a legacy scope. Can we still add it to new apps?

**Comment by tulir** [comment]
As I said, the permissions you pick don't matter. I just added `identity.basic` as a placeholder to let me enable distribution.

**Comment by joao-p-marques** [comment]
Ok. It worked! Thank you! 

As I said, I don't know much about Slack apps, and this helped a lot!
