### ISSUE TITLE
With new namepatterns, slack groups without names are unrecognizable strings

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#31]
In slack you can create rooms with no names, and the name inside slack defaults to a list of the participants usernames. 
![image](https://user-images.githubusercontent.com/1048265/73098219-c38ff300-3e9d-11ea-8ad4-8fafe6bc8fea.png)

Previously the slack bridge would mimic this, but now it creates a weird long string instead of list of names

![image](https://user-images.githubusercontent.com/1048265/73098201-ba068b00-3e9d-11ea-9c51-d9281be7547d.png)

**Comment by Sorunome** [comment]
Duplicate of #6

**Comment by ericmigi** [comment]
sort of the same, except now these are even less understandable :/
