### ISSUE TITLE
Bridge fails to initialize correctly if synapse is unreachable

### ISSUE THREAD

**Issue by Cadair** [Sorunome/mx-puppet-slack#37]
The bridge responds to commands once synapse has restored, but it has failed to connect to slack, restarting the bridge with synapse active fixes the issue.

**Comment by Sorunome** [comment]
So you are saying that, if you start the bridge while synapse is offline, the bridge does not connect to slack at all?

**Comment by Cadair** [comment]
This seems to be my observation, it's hard to exactly pin down.

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/dda4a9e0f1a195e1d60a389a9cb5e015ec9f9d64
