### ISSUE TITLE
My Slack user automatically joins any new public rooms

### ISSUE THREAD

**Issue by jeffcasavant** [Sorunome/mx-puppet-slack#53]
version b1b142bb9d6fa3924d4469854141550f64afd809
double-puppeting - tested with both on & off, behavior is the same
backend - postgres
autoinvite - off

Matrix-side, I do not get an invite/autojoined.  Slack-side, my user joins the channel as soon as it's created, without anything triggering it.

When I have mx-puppet-slack off, I do not see this behavior.

I would expect that when new public channels are created, I do not join them by default.  Being invited or joining manually should be the only ways I get into a room.

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/soru-slack-client/commit/7eea083066e96dec7e6d7228f797ef73255b12bf
