### ISSUE TITLE
group unnamed rooms are bridged slightly incorrectly

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#6]
this is a nameless group, in slack appears like this,
![image](https://user-images.githubusercontent.com/1048265/60631770-f9607380-9db5-11e9-9e17-55767febf6b4.png)

in riot like this

![image](https://user-images.githubusercontent.com/1048265/60631762-ea79c100-9db5-11e9-80c7-31c56cfb318f.png)

**Comment by Sorunome** [comment]
Should be fixed in https://github.com/Sorunome/mx-puppet-bridge/commit/f117e6eae21a6bb7baaedaf9950c3d1488120ecf
