### ISSUE TITLE
slack private groups are not bridged slack>matrix

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#66]
![image](https://user-images.githubusercontent.com/1048265/81759563-e577aa80-9479-11ea-8982-c41a4a2e8320.png)

The `dmitry, novaeric, Tech Support` group is not bridged at all. Very reproducible.

**Comment by ericmigi** [comment]
was bug in my riot, not bridge problem

**Comment by ericmigi** [comment]
actually, wasn't riot. still occurring even with riot.im/app

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/soru-slack-client/pull/8
