### ISSUE TITLE
bot messages missing images

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#7]
here's a slackbot message that is missing an image. Probably tough to cram the formatting into Matrix, but hopefully possible to get the image

![image](https://user-images.githubusercontent.com/1048265/60631812-48a6a400-9db6-11e9-942c-8193d772a059.png)

in slack
![image](https://user-images.githubusercontent.com/1048265/60631817-50664880-9db6-11e9-8123-7c6d00ae3cfb.png)

**Comment by Sorunome** [comment]
Probably fixed by now with the new slack message parser. Please make a new issue if this is still the case (preferably in https://github.com/Sorunome/matrix-slack-parser/ but either is fine)
