### ISSUE TITLE
Better mpim channel names 

### ISSUE THREAD

**Issue by matejdro** [Sorunome/mx-puppet-slack#72]
Currently names of mpim channels are not very useful:

![image](https://user-images.githubusercontent.com/507922/82992238-271e5e80-9fff-11ea-9ba0-405b03dc3a10.png)

It would be helpful if channel would be named from list of people inside, similar to how native slack client does it.

**Comment by Sorunome** [comment]
This is a bug with riot-web, as it uses `alt_aliases` to calculate the room name while the spec clearly forbids so.

**Comment by matejdro** [comment]
Can you link to the riot issue?

**Comment by Sorunome** [comment]
not sure there is one yet :/

**Comment by matejdro** [comment]
Can you create one? I would do it, but I do not know the details of the issue.

**Comment by Sorunome** [comment]
closed in favour of #50
