### ISSUE TITLE
Images not bridged slack -> matrix for xoxc puppets

### ISSUE THREAD

**Issue by lukeceddia** [Sorunome/mx-puppet-slack#73]
The "image" file that gets sent to the matrix server is actually HTML of the Slack login page.

**Comment by seanfarley** [comment]
Yep, can confirm. This is also broken for me.

**Comment by lukeceddia** [comment]
This can be fixed by also passing the d cookie at [https://github.com/Sorunome/soru-slack-client/blob/8f6449a8d6f75c406a972fa18d97b895cd103651/src/structures/client.ts#L769](https://github.com/Sorunome/soru-slack-client/blob/8f6449a8d6f75c406a972fa18d97b895cd103651/src/structures/client.ts#L769). In fact, it works without the Authorization header too.

I don't know how the oauth-based puppet works though, so I'm hesitant to just submit a PR that replaces the current header with the cookie.

**Comment by Sorunome** [comment]
should be fixed now
