### ISSUE TITLE
Support xoxs tokens

### ISSUE THREAD

**Issue by Sorunome** [Sorunome/mx-puppet-slack#79]
https://github.com/jackellenberger/emojme#slack-for-web

**Comment by MurzNN** [comment]
Looking to readme https://github.com/Sorunome/mx-puppet-slack#xoxc-token - seems this feature is already implemented? Or you have plans to improve it?

**Comment by auscompgeek** [comment]
@MurzNN xoxc tokens are not xoxs tokens.

I suspect no additional code would even be required for xoxs tokens, for the most part.

**Comment by auscompgeek** [comment]
It'd be great if using session tokens were recommended over client tokens. I have yet to find any bugs that affect the bridge using session tokens.

**Comment by Sorunome** [comment]
Confirmed everything working, documented in https://github.com/Sorunome/mx-puppet-slack/commit/291bbc270cb144613b0c6b6201042eaf8db20afc
