### ISSUE TITLE
feature request: add link to the slack channel/message in the matrix source

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#8]
so if user wants to click view source, they can get a url that deep links them back into slack web client directly to that message. is this even possible?

low priority but cool if possible

**Comment by twouters** [comment]
I guess that's what [external_url](https://matrix.org/docs/spec/application_service/r0.1.1#referencing-messages-from-a-third-party-network) is for?

**Comment by Sorunome** [comment]
Done in https://github.com/Sorunome/mx-puppet-slack/commit/4f4f6edd829e4bebcc72112c57cb82270b360f60
