### ISSUE TITLE
Relay with xoxc token does not show username

### ISSUE THREAD

**Issue by johannes-krude** [Sorunome/mx-puppet-slack#88]
mx-puppet-slack has `advancedRelay: true`, therefore mx-puppet-bridge does not prepend the username before a relay message.

However, a relay which uses an xoxc token can not change username, therefore the sender username is lost in slack.

**Comment by Sorunome** [comment]
It should be added back, though: https://github.com/Sorunome/mx-puppet-slack/blob/master/src/slack.ts#L498

How did you create the puppet?

**Comment by Sorunome** [comment]
AAAAAAH it edits the markdown text but not the slack blocks, and as an xoxc token is actually allowed to send those then it doesn't show! Gotcha, working on it

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-slack/commit/10aef4d20ec4367fecf36319418d039e5cfbd682
