### ISSUE TITLE
one-on-one chats don't have the slack name eg - YC after the persons name

### ISSUE THREAD

**Issue by ericmigi** [Sorunome/mx-puppet-slack#9]
![image](https://user-images.githubusercontent.com/1048265/60631976-63c5e380-9db7-11e9-8487-9a3f096b91f8.png)

**Comment by ericmigi** [comment]
should be kat - YC

**Comment by Sorunome** [comment]
that is actually also currently intended behaviour: the bridge sets neither an avatar nor a name, thus the client displays the avatar and name of the other participant

**Comment by ericmigi** [comment]
for now, I think it would be best to have the bridge name the portal "username - slackname Slack" so from a filtering perspective it's easy to ctl-k search for the user and differentiate from other portals you might have with other people

**Comment by Sorunome** [comment]
This is fixed with the name patterns
