### ISSUE TITLE
Reactions with skin tone modifiers show up as just skin tones

### ISSUE THREAD

**Issue by vpzomtrrfrt** [Sorunome/mx-puppet-slack#93]
In Slack:
![image](https://user-images.githubusercontent.com/3528358/98993718-10f05600-24ec-11eb-9c40-58bbb4df9313.png)

In Matrix:
![image](https://user-images.githubusercontent.com/3528358/98993772-21a0cc00-24ec-11eb-91ac-28c43f2269a5.png)

**Comment by tchapi** [comment]
Same here. Any workaround for that for now ? Or any hint on where in the code it is managed so we can try a PR ?

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/mx-puppet-slack/commit/0f87dd6d8bccfb756b942c89b6e3e67634fbb81c
