### ISSUE TITLE
Wrong formatting of Matrix code blocks into Slack channel message

### ISSUE THREAD

**Issue by MurzNN** [Sorunome/mx-puppet-slack#94]
When I compose those message on Matrix side ( " ` " is replaced to " ' " for keep formatting):
```
test
'''
code
'''
test2
```

And send to room, bridged to Slack, I see on Slack side it as:
```
test<code>code
</code>test2
```

Backwards encoding works well, so if I post message on Slack side with code blocks - they converted to Matrix code blocks successfully.

**Comment by nivekuil** [comment]
I was experiencing formatting weirdness too but the latest commit seems to have fixed it. Thanks @Sorunome <3

**Comment by MurzNN** [comment]
Yes, fixed!
