### ISSUE TITLE
Wrong formatting of sent Matrix replies messages in Slack side

### ISSUE THREAD

**Issue by MurzNN** [Sorunome/mx-puppet-slack#95]
When I send a reply to some message from Matrix, it formatted on Slack side badly, via plaintext, here is screenshots on Matrix side:
![image](https://user-images.githubusercontent.com/336662/99076695-99462800-25cc-11eb-8d59-e16edfa1f437.png)
And on Slack side Thread:
![image](https://user-images.githubusercontent.com/336662/99076728-abc06180-25cc-11eb-9d83-09607bbb4420.png)
Can this been fixed via any way?

**Comment by Sorunome** [comment]
The html parser used to parse matrix messages had a breaking change with a minor version bump. that is fixed now.

**Comment by mdkcore0** [comment]
the "in reply to" text is expected to appear on the Slack side as well? it is happening with me with the latest docker image
![image](https://user-images.githubusercontent.com/1218078/101953514-4070ac00-3bd9-11eb-95c6-8f1f3ee9fc97.png)
