### ISSUE TITLE
Bridge trim spaces in code blocks on Slack side from Matrix messages

### ISSUE THREAD

**Issue by MurzNN** [Sorunome/mx-puppet-slack#97]
I got a problem, that bridge do the trim spaces at beginning and end of code blocks on Slack side from Matrix messages, here is example - Matrix side:
![image](https://user-images.githubusercontent.com/336662/99776376-c55c2e80-2b21-11eb-9aa7-4385a4c922a4.png)
Slack side:
![image](https://user-images.githubusercontent.com/336662/99776399-d0af5a00-2b21-11eb-854d-b4e96506b2df.png)

Can you please fix this? Thanks!

**Comment by MurzNN** [comment]
Also there are strange problem (maybe related), than if I try to edit message with code blocks, sent via Matrix,  in Slack interface, whole message becomes as code, instead of only code block, here is example:
![image](https://user-images.githubusercontent.com/336662/99776546-0e13e780-2b22-11eb-88fc-4f32f3d3e306.png)

**Comment by MurzNN** [comment]
And third problem with code blocks - if I try to edit message, sent from Slack, in Matrix, the line breaks in code block are disappear:
![image](https://user-images.githubusercontent.com/336662/99777017-c2157280-2b22-11eb-8588-02790f28ce2f.png)

**Comment by Sorunome** [comment]
The edits being broken is an element issue, so please report that at them, not here.

**Comment by Sorunome** [comment]
And soru does not plan on supporting proper cross-edit support, it's too much a hassle

**Comment by Sorunome** [comment]
Fixed in https://github.com/Sorunome/mx-puppet-slack/commit/75e412075e978b41b1f78583f5b31a2ec985e218

**Comment by MurzNN** [comment]
Thanks for quick fixing!

About "_if I try to edit message, sent from Slack, in Matrix, the line breaks in code block are disappear_" - the source of problem is with missing line break before closing codeblock markup, here is example:

Native Matrix message body:
```
"body": "Test code block indent in Matrix message:\n```\n        indent 8 one\n        indent 8 two 2\n```",
```

Bridged from Slack message body:
```
"body": "Test code block indent in Slack message:\n```        indent 8 one\n        indent 8 two```",
```
I see missing `\n` before closing "```" markup. Can you please fix this too?

**Comment by MurzNN** [comment]
Maybe replacing this line: https://github.com/Sorunome/matrix-slack-parser/blob/master/src/matrixmessageparser.ts#L202
```
				text: `\`\`\`${text}\`\`\`\n`,
```
to
```
				text: `\`\`\`\n${text}\n\`\`\`\n`,
```
will help? I'll try to change this in my setup and report results.

**Comment by Sorunome** [comment]
Is slack not using the internal code blocks?

**Comment by MurzNN** [comment]
By "internal" you mean "inline"? They marked up via one "`" symbol, not three. I will try to debug this thing more detailed...

**Comment by Sorunome** [comment]
no, soru means slack blocks: https://api.slack.com/block-kit there are a bunch of undocumented internal ones which slack *actually* uses fro rendering messages, it ignores the mrkdwn

**Comment by MurzNN** [comment]
On frontend side (web interface) they send to server a json, not plaintext:
```
[{"type":"rich_text","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Test markdown:\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"line 1\nline 2"}]}]}]
```

**Comment by Sorunome** [comment]
Yes, and that is exactly what the bridge sends, too
